import Header from '@/components/interface/Header'
import Head from 'next/head'
import Image from "next/image"

// import img_1 from '../lib/images/fa/img_01.png';
// import img_2 from '../lib/images/fa/img_02.png';
// const inter = Inter({ subsets: ['latin'] })

import arroz from '../lib/images/produtos/arroz.png';
import roupas from '../lib/images/produtos/roupas.png';
import cuscuz from '../lib/images/produtos/cuscuz.png';
import leite from '../lib/images/produtos/leite.png';
import fralda from '../lib/images/produtos/fralda.png';


export default function Home() {
  return (
    <>
      <Head>
        <title>SMSG - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="container mt-3">
          <div className="row">
            {/* Listagem de produtos destaques */}
            <h3>Itens em destaque</h3>
          </div>
          <div className="row">
            {/* Listagem de produtos no mercado */}
            <div className="col-md-4">
              <div className="card">
                <Image className="card-img-top" src={arroz} alt="produto" style={{ height: '10rem' }} />
                <div className="card-body">
                  <h5 className="card-title">Produto 1</h5>
                  <p className="card-text">Descrição do Produto 1.</p>
                  <h6 className="card-subtitle mb-2 text-muted">Preço: R$ 99,99</h6>
                  <a href="#" className="btn btn-olive" style={{ backgroundColor: '#b3d353' }}>Comprar</a>
                </div>
              </div>
            </div>

            <div className="col-md-4">
              <div className="card">
                <Image className="card-img-top" src={roupas} alt="produto" style={{ height: '10rem' }} />
                <div className="card-body">
                  <h5 className="card-title">Produto 2</h5>
                  <p className="card-text">Descrição do Produto 2.</p>
                  <h6 className="card-subtitle mb-2 text-muted">Preço: R$ 149,99</h6>
                  <a href="#" className="btn btn-olive" style={{ backgroundColor: '#b3d353' }}>Comprar</a>
                </div>
              </div>
            </div>

            <div className="col-md-4">
              <div className="card">
                <Image className="card-img-top" src={cuscuz} alt="produto" style={{ height: '10rem' }} />
                <div className="card-body">
                  <h5 className="card-title">Produto 3</h5>
                  <p className="card-text">Descrição do Produto 3.</p>
                  <h6 className="card-subtitle mb-2 text-muted">Preço: R$ 199,99</h6>
                  <a href="#" className="btn btn-olive" style={{ backgroundColor: '#b3d353' }}>Comprar</a>
                </div>
              </div>
            </div>

            <div className="col-md-4">
              <div className="card">
                <Image className="card-img-top" src={leite} alt="produto" style={{ height: '10rem' }} />
                <div className="card-body">
                  <h5 className="card-title">Produto 3</h5>
                  <p className="card-text">Descrição do Produto 3.</p>
                  <h6 className="card-subtitle mb-2 text-muted">Preço: R$ 199,99</h6>
                  <a href="#" className="btn btn-olive" style={{ backgroundColor: '#b3d353' }}>Comprar</a>
                </div>
              </div>
            </div>

            <div className="col-md-4">
              <div className="card">
                <Image className="card-img-top" src={fralda} alt="produto" style={{ height: '10rem' }} />
                <div className="card-body">
                  <h5 className="card-title">Produto 3</h5>
                  <p className="card-text">Descrição do Produto 3.</p>
                  <h6 className="card-subtitle mb-2 text-muted">Preço: R$ 199,99</h6>
                  <a href="#" className="btn btn-olive" style={{ backgroundColor: '#b3d353' }}>Comprar</a>
                </div>
              </div>
            </div>

          </div>
        </div>
      </main>
    </>
  )
}
